bookers-level2/config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :books, only: [:create, :index, :show, :edit, :update, :destroy]
  resources :users, only: [:create, :index, :show, :edit, :update]
  root 'users#home'
  get "home/about" => 'users#about', as:"home_about"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

bookers-level2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookers-level2/app/models/book.rb
class Book < ApplicationRecord

  validates :book_name, presence: true
  validates :caption, presence: true, length: { maximum: 200 }

	belongs_to :user

end

bookers-level2/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  validates :name, presence: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :books, dependent: :destroy

  attachment :profile_image

end

bookers-level2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller? 

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name,:email])
  end

  def after_sign_in_path_for(resources)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

end

bookers-level2/app/controllers/books_controller.rb
class BooksController < ApplicationController

before_action :authenticate_user!

before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def ensure_correct_user
   @libro = Book.find(params[:id])
    if current_user.id != @libro.user_id
       flash[:notice] = "error!!"
       redirect_to user_path(current_user.id)
    end
end

  def show
    @book = Book.new
    @libro = Book.find(params[:id])
  end

  def index
  	@books = Book.all
  	@book = Book.new
  end

  def create
    book = Book.new(book_params)
    book.user_id = current_user.id
    if book.save
       redirect_to book_path(book.id)
       flash[:notice] = 'Book was successfully created.'
    else
       redirect_to books_path
       flash[:notice] = 'create error!!'
     end
  end

  def edit
    @libro = Book.find(params[:id])
  end

  def update
    libro = Book.find(params[:id])
      if  libro.update(book_params)
        redirect_to book_path(libro.id)
        flash[:notice] = 'Book was successfully updated.'
      else
        redirect_to edit_book_path(libro.id)
        flash[:notice] = 'update error!!'
      end
  end

  def destroy
    libro = Book.find(params[:id])
        if libro.destroy
           redirect_to books_path
           flash[:notice] = 'Book was successfully destroyed.'
        else
           render book_path(libro.id)
           flash[:notice] = 'destroy error!!'
        end
  end


    private

    def book_params
      params.require(:book).permit(:book_name, :caption)
    end

end

bookers-level2/app/controllers/users_controller.rb
class UsersController < ApplicationController


  def home
  end

  def about
  end

before_action :authenticate_user!, only: [:create, :index, :show, :edit, :update]

before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def ensure_correct_user
   @user = User.find(params[:id])
    if current_user.id != @user.id
       flash[:notice] = "error!!"
       redirect_to user_path(current_user.id)
    end
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

	def index
  	@book = Book.new
  	@users = User.all
  end

  def create
  	  book = Book.new(book_params)
  	  book.user_id = current_user.id
      if book.save
         redirect_to book_path(book.id)
         flash[:notice] = 'Book was successfully created.'
      else
        redirect_to books_path
        flash[:notice] = 'create error!!'
      end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
      if @user.update(user_params)
       redirect_to user_path(@user.id)
       flash[:notice] = 'Book was successfully updated.'
      else
       redirect_to edit_user_path(@user.id)
        flash[:notice] = 'update error!!'
      end
  end

    private

    def user_params
      params.require(:user).permit(:name, :profile_image, :introduction)
    end
end

bookers-level2/app/helpers/application_helper.rb
module ApplicationHelper
end

bookers-level2/app/helpers/books_helper.rb
module BooksHelper
end

bookers-level2/app/helpers/users_helper.rb
module UsersHelper
end

bookers-level2/app/views/books/edit.html.erb
<main>
<h1>Editing Book</h1>
<!-- form_for部分 -->
  <%= form_for(@libro) do |f| %>

    <h4>Title</h4>
    <%= f.text_field :book_name, class:"book_title" %>

    <h4>Body</h4>
    <%= f.text_area :caption, class:"book_body" %>

    <br><%= f.submit 'Update Book' %></br>

  <% end %>
</main>

<%= link_to "Show", book_path(@libro.id), class:"book_#{@libro.id}" %>
|
<%= link_to "Back", books_path, class:"back" %>

bookers-level2/app/views/books/index.html.erb
<div class="container">
<div class="row">
  <div class="col-xs-4" style="background-color: orange;">

    <%= render 'users/info', user: current_user %>

  </div>

  <div class="col-xs-8" style="background-color: pink;">
	<h2>Books</h2>
		<table class="table table-striped">
			<thead>
				<tr>
					<th>photo欄あとで消す！！</th>
					<th>Title</th>
					<th>Opinion</th>
				</tr>
			</thead>
			<tbody>
			<% @books.each do |book| %>
				<tr>
					<td><%= attachment_image_tag book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></td>
					<td><%= link_to book_path(book.id), class: "book_#{book.id}" do %>
					<%= book.book_name %>
					    <% end %>
					</td>
					<td><%= book.caption %></td>
				</tr>
			<% end %>
			</tbody>
		</table>
  </div>
</div>
</div>

bookers-level2/app/views/books/show.html.erb
<div class="container">
<div class="row">
  <div class="col-lg-4">
        <%= render 'users/info', user: @libro.user %>

  </div>

  <div class="col-lg-8">
	<h2>Book details</h2>
		<table class="table table-striped">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion<th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td><%= attachment_image_tag @libro.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
					</td>
					<td><%= link_to edit_book_path(@libro.id), class:"edit_book_#{@libro.id}" do %>
					    <%= @libro.book_name %>
					    <% end %>
					</td>
					<td>
				        <%= @libro.caption %>
					</td>
					<td>
						<% if @libro.user_id == current_user.id %>
						  <%= link_to "Edit", edit_book_path(@libro.id), class:"edit_book_#{@libro.id}" %>
                          <%= link_to "Destroy", book_path(@libro.id), method: :delete, "data-confirm" => "Are you sure?", class:"destroy_book_#{@libro.id}"%>
                        <% end %>
					</td>
				</tr>
			</tbody>
		</table>
  </div>
</div>
</div>

bookers-level2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookersLevel2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="menu">
    <ul class="nav navbar-nav navbar-right">
    <% if user_signed_in? %>
      <li role="presentation">
        <span class="glyphicon glyphicon-home" aria-hidden="true">
          <%= link_to 'Home', user_path(current_user.id), class: "home" %>
        </span>
      </li>
      <li role="presentation">
        <span class="glyphicon glyphicon-user" aria-hidden="true">
          <%= link_to 'Users', users_path, class: "users" %>
        </span>
      </li>
      <li role="presentation">
        <span class="glyphicon glyphicon-book" aria-hidden="true">
          <%= link_to 'Books', books_path, class: "books" %>
        </span>
      </li>
      <li role="presentation">
        <span class="glyphicon glyphicon-log-out" aria-hidden="true">
          <%= link_to "logout", destroy_user_session_path, method: :delete, class: "logout" %>
        </span>
      </li>
    <% else %>
      <li role="presentation">
        <span class="glyphicon glyphicon-home" aria-hidden="true">
          <%= link_to 'Home', user_path(current_user.id), class: "home" %>
        </span>
      </li>
      <li role="presentation">
        <span class="glyphicon glyphicon-link" aria-hidden="true">
          <%= link_to 'About', home_about_path, class: "about" %>
        </span>
      </li>
      <li role="presentation">
        <span class="glyphicon glyphicon-edit" aria-hidden="true">
          <%= link_to "Sing up", new_user_registration_path, class: "sign_up" %>
        </span>
      </li>
      <li role="presentation">
        <span class="glyphicon glyphicon-log-in" aria-hidden="true">
          <%= link_to "Sing in", new_user_session_path, class: "sign_in" %>
        </span>
      </li>
    <% end %>
    </ul>
    </div>

<% if flash[:notice] %>
<p id=notice><%= flash[:notice] %></p>
<% end %>
    <%= yield %>
  </body>
</html>

bookers-level2/app/views/users/_info.html.erb
	<div class="sidebar-user">
		<h2> User info</h2>
		<table class="table table-striped">
			<div class="profile-container">
                <%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
            </div>
			<thead>
				<tr>
					<th>name</th>
					<th>introduction</th>
				</tr>
			</thead>
			<tbody>
				<tr>
                    <td><%= user.name %></td>
					<td><%= user.introduction %></td>
				</tr>
			</tbody>
		</table>
	    <% if user.id == current_user.id %>
            <p><%= link_to "プロフィール編集", edit_user_path(user), class: "edit_user_#{user.id}" %></p>
        <% end %>
	</div>
 <div class="sidebar-new">
		<h2>New book</h2>
		<!-- form_for部分 -->
		<%= form_for(@book) do |f| %>

    		<div>Title</div>
    		<%= f.text_field :book_name, class:"book_title" %>

    		<div>Opinion</div>
    		<%= f.text_area :caption, class:"book_body" %>

    		<div><%= f.submit 'Create Book' %></div>

		<% end %>
	</div>
</div>

bookers-level2/app/views/users/about.html.erb
<h1>Welcome to Bookers!</h1>
<p>This page is "About"!!</p>

bookers-level2/app/views/users/edit.html.erb
<h1>User info</h1>

<!-- form_for部分 -->
  <%= form_for(@user) do |f| %>

<div>
    <h4>Name</h4>
    <%= f.text_field :name, class: "name" %>
    <h4>Introduction</h4>
    <%= f.text_field :introduction, class: "introduction" %>
</div>

<div class="form-group has-icon">
    <div class="user-edit-image">
        <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%>
    </div>
    <label class="control-label sr-only" for="inputEmail">ProfileImage</label>
    <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user_image" %>
</div>

    <br><%= f.submit 'Update User' %></br>

  <% end %>
</main>

bookers-level2/app/views/users/home.html.erb
<h1>welcome to Bookers !!</h1>
<span>In <strong>Bookers</strong>,</span>

<p>you can share and exchange your opinions , inpressions , and emotions<br>
about varioius books!</p>

<div><%= link_to "Sing up", new_user_registration_path, class:"sign_up" %></div>
<div><%= link_to "Sing in", new_user_session_path, class:"sign_in" %></div>

bookers-level2/app/views/users/index.html.erb
<div class="sidebar">

<%= render 'users/info', user: current_user %>

<main>
	<h2>Users</h2>
		<table class="table table-striped">
			<thead>
				<tr>
					<th>image</th>
					<th>name</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
			<% @users.each do |user| %>
				<tr>
					<td><%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></td>
					<td><%= user.name %></td>
					<td><%= link_to "Show", user_path(user.id), class:"user_#{user.id}" %></td>
				</tr>
			<% end %>
			</tbody>
		</table>
</main>

bookers-level2/app/views/users/show.html.erb
<div class="sidebar">

<%= render 'users/info', user: @user %>

<main>
	<h2>Books</h2>
		<table class="table table-striped">
			<thead>
				<tr>
					<th>photo欄あとで消す！！</th>
					<th>Title</th>
					<th>Opinion</th>
				</tr>
			</thead>
			<tbody>
			  <% @books.each do |book| %>
				<tr>
					<td><%= attachment_image_tag book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></td>
					<td>
						<%= link_to book_path(book.id), class:"book_#{book.id}" do %>
					        <%= book.book_name %>
					    <% end %>
					</td>
					<td>    <%= book.caption %></td>
				</tr>
			  <% end %>
			</tbody>
		</table>
</main>